apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice
  namespace: ingress-nginx
spec:
  project: default
  source:
    path: components/ingress-nginx
    repoURL: https://github.com/simonecastellani/kustomize-workshop # Update with your repo URL
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
