apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# includes the base configuration for the shop application
resources:
  - ../../../../components/argocd/base
  - clusters-secrets.yaml
  - repos-secrets.yaml

  - ../../../../components/argoproj/
