apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - deploy-argocd.yaml
  - ingress.yaml

patches:
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: argocd
    target:
      kind: ClusterRoleBinding


  - path: patch-service.yaml