apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice1-nginx-config
data:
   nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 10240;
    }
    http {
      server {
        listen 8000;
        location / {
          default_type application/json;
          return 200 '{"app": "microservice1", "request_uri": "$request_uri", "Authorization": "$http_authorization", "remote_addr": "$remote_addr", "http_x_forwarded_for": "$http_x_forwarded_for", "http_x_request_id": "$http_x_request_id"}';
        }
      }
    }

